# Generated by Django 3.2.12 on 2022-04-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('idno', models.CharField(max_length=255, null=True, unique=True)),
                ('register_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('organization_form', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('managers', models.JSONField(null=True)),
                ('cuatm', models.CharField(max_length=255, null=True)),
                ('founders', models.JSONField(null=True)),
                ('beneficiaries', models.JSONField(null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('liquidation_date', models.DateTimeField(null=True)),
                ('licensed_activities', models.JSONField(null=True)),
                ('unlicensed_activities', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('change', models.JSONField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_changes', to='companies_11736.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
