# Generated by Django 3.2.12 on 2022-04-11 14:16

import apps.resource.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('file_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('licensee', models.CharField(max_length=255, null=True)),
                ('format', models.CharField(max_length=100, null=True)),
                ('mimetype', models.CharField(max_length=255, null=True)),
                ('resource_group_id', models.CharField(max_length=255, null=True)),
                ('resource_type', models.CharField(max_length=100, null=True)),
                ('revision_id', models.CharField(max_length=255, null=True)),
                ('size', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('parsed', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=apps.resource.models.upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceListScanTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('resource_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resource.resourcelist')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
